services:
  - type: web
    name: mini-sudoku-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MINI_SUDOKU_SECRET
        sync: false
      - key: PUBLIC_ORIGIN
<<<<<<< HEAD
        sync: false
=======
        sync: false
>>>>>>> 999898fb12414e39433ead118c53f63076387f0c
