services:
  - type: web
    name: mini-sudoku-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MINI_SUDOKU_SECRET
        sync: false
      - key: PUBLIC_ORIGIN
        sync: false
